site_name: My Obsidian Notes

site_url: https://arkserks.github.io/my_obsidian

theme:
  name: material

plugins:
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

